### ISSUE TITLE
Using with React Native

### ISSUE THREAD

**Issue by AstRonin** [bietkul/react-reactive-form#1]
Can we use this library with react-native? Or need add some router for that?

**Comment by bietkul** [comment]
Yes, you can use it with react-native, without any configuration.

**Comment by AstRonin** [comment]
Back to my question... Did you tested it on mobile platform?
I tried to add library but input did not allowed set any symbols. In code I found method in **model.js,  getControlValue()** where
RN return **undefined** of **event.target.type**, **event.target.value** and others which works in a browser... It seams like RN does not know about this properties...
RN using the various inputs [TextInput](https://facebook.github.io/react-native/docs/textinput.html), [Switch](https://facebook.github.io/react-native/docs/switch.html)... I suppose events in RN are different of ReactJS...
So, I think need to add some cases for getting values from RN input components...
For example, for **TextInput** Component match more easy get value from **onChangeText** callback.

**Comment by bietkul** [comment]
Thanks for figuring it out.
It has been fixed in the latest version.
