### ISSUE TITLE
how to inject external props into the react-form .props not able to print in the form

### ISSUE THREAD

**Issue by sred36** [bietkul/react-reactive-form#10]
this.props.dbList iam receiveing props from API But i am not able to print inside the FieldControl
But i can able to print in render method not in form,Can you provide some examples  to inject props into FiedComtrol
<FieldGroup
                control={this.mssqlForm}
                render={({ get, invalid }) => (
                    <form>
<FieldControl
                            name="dbname"
                            render={({ handler, touched, hasError }: AbstractControl) => (
                                <div>
                                    <label>DBname:</label>
                                    <select className={`form-control`} {...handler()}>
                                        {
                                            this.props.dbList.map((datasource, index) => {
                                                return (
                                                    <option
                                                        key={index}
                                                    > {datasource}
                                                    </option>
                                                );
                                            })
                                        }
                                    </select>
                                </div>
                            )}
                        />

**Comment by bietkul** [comment]
Actually the default value of `strict` is `true`.
Please change it to false & it should work.

```js
 <FieldControl
     name="dbname"
     strict={false}
    />
```

**Comment by sred36** [comment]
Hi @bietkul,

i tried both still its not working

**Comment by sred36** [comment]
it is working now,when i use like this
 <FieldGroup
     strict={false}  
/>

Thanks lot..

**Comment by bietkul** [comment]
Cool 👍
