### ISSUE TITLE
onBlur callback on FieldControl

### ISSUE THREAD

**Issue by omerkhawaja** [bietkul/react-reactive-form#17]
Let's say I have a text input that on `onFocus` triggers a menu popover to be visible, and when `onBlur` occurs, the menu is removed.

Is there a way to use `onFocus` for this type of functionality?  I'm not seeing `onFocus` support in the documentation.

It appears that `    updateOn: PropTypes.oneOf(['change', 'blur', 'submit'])` doesn't support `focus`, but I thought I'd ask.

**Comment by bietkul** [comment]
Yes, there is no support for `onFocus` in RRF now.
