### ISSUE TITLE
Unable to import FormBuilder via Typescript

### ISSUE THREAD

**Issue by dannyhuly** [bietkul/react-reactive-form#27]
Hi,
I'm trying to use `react-reactive-form` in a `.tsx` but i'm unable to import `FormBuilder` or anything under the [`react-reactive-form` module](https://github.com/bietkul/react-reactive-form/blob/9c2082720600bbe1552f086060c9ddc744add6eb/index.d.ts#L338).

The only thing that i'm able to import is `AbstractControl`.

Thanks

**Comment by bietkul** [comment]
I don't know what can be issue with you but I have a working example with typescript.
https://codesandbox.io/s/4rxokpr270

**Comment by dannyhuly** [comment]
The sandbox does't support module resolution validation.
In your example you are able to import whatever you like from any module.
see the following https://codesandbox.io/s/04m58wqy6l.


Github have issues currently ([status](https://status.github.com/messages/2018-10-22)) so i'm unable to send a PR to for a fix.
But removing the `declare module ['react-reactive-form'` ](https://github.com/bietkul/react-reactive-form/blob/9c2082720600bbe1552f086060c9ddc744add6eb/index.d.ts#L338) encapsulation will fix the typing.

**Comment by dannyhuly** [comment]
The sandbox allows you to import whatever you like (see: https://codesandbox.io/s/l92k6kwox9).

The fix is to remove the [`declare module 'react-reactive-form'`](https://github.com/bietkul/react-reactive-form/blob/9c2082720600bbe1552f086060c9ddc744add6eb/index.d.ts#L338) from the `index.d.ts`.

I would open a PR but Github is a bit wonky today.
