### ISSUE TITLE
Autosave option

### ISSUE THREAD

**Issue by muhammadnasr** [bietkul/react-reactive-form#34]
Thanks for the great lib.

Do you have option for autosave like 

https://www.npmjs.com/package/react-distributed-forms

check the demo to see how it works.
https://codesandbox.io/s/5k30y1x05k

**Comment by bietkul** [comment]
Hey, I think that is more like a React state implementation which can also be implemented with this library.
You can use `handleSubmit` function from control to make a form as submitted.
Refer docs: 
https://github.com/bietkul/react-reactive-form/blob/master/docs/api/FormGroup.md

**Comment by bietkul** [comment]
It seems like the issue is not active anymore.
closing it, for now, feel free to re-open
