### ISSUE TITLE
Using the library with create-react-app 

### ISSUE THREAD

**Issue by Michael-D-Pine** [bietkul/react-reactive-form#4]
Hi,

getting issues such as below when I try the library out, installs ok but as soon as I try and import anything even just FormBuilder I get the following issue.

./node_modules/react-reactive-form/src/FieldGroup.js
Module parse failed: Unexpected token (20:6)
You may need an appropriate loader to handle this file type.
|     const { strict, children, render } = this.props
|     return (
|       <Field
|         control={this.control}
|         strict={strict}

**Comment by bietkul** [comment]
Please try it now, this issue has been resolved in the latest version.

**Comment by Michael-D-Pine** [comment]
*Thumbs up*

Updated to latest version and all looks good, thanks!

regards
Michael
