### ISSUE TITLE
Can't add separate Fields

### ISSUE THREAD

**Issue by aturan23** [bietkul/react-reactive-form#41]
**Describe the bug**
I use FormGenerator. And I customized my form component and used it. But when I use separate fields it's render just first one. I changed order of fields but just first one on dialog

**Screenshots**
![image](https://user-images.githubusercontent.com/26896845/59091833-fa76c000-8931-11e9-848d-b562aca31dcf.png)

**Desktop (please complete the following information):**
 - MacOs Mojave 10.14.3
- [package.json](https://gist.github.com/aturan23/7e81240b98f129cbda041c3fc2d63da4)
- [Autocomplate function&class](https://gist.github.com/aturan23/629fd8b25c89fae9d1cb4943a3fb3bcb)

**Additional context**
how I create:
```
controls: {
        autosuggestion: {
            render: (control) => <AutocomplateField {...control} />,
            meta : {
                label: "some"
            }
        },
        downshift: {
            render: (control) => <IntegrationDownshift {...control}/>,
            meta: {
                label: 'downshift'
            }
        }
    }
```

**Comment by bietkul** [comment]
What does your `IntegrationDownshift` component render?

**Comment by aturan23** [comment]
> What does your `IntegrationDownshift` component render?

@bietkul its material-ui field. u can see it [here](https://gist.github.com/aturan23/d6bdccc6b2c7d646b0b81489c7b656f2)

**Comment by bietkul** [comment]
I'm not sure, something is off with this component.
Can you please share a code sandbox link with an example.

**Comment by aturan23** [comment]
> I'm not sure, something is off with this component.
> Can you please share a code sandbox link with an example.
@bietkul 
[Here](https://codesandbox.io/s/create-react-app-sktxl?fontsize=14)

**Comment by aturan23** [comment]
> I'm not sure, something is off with this component.
> Can you please share a code sandbox link with an example.

@bietkul [here](https://codesandbox.io/s/create-react-app-sktxl?fontsize=14)

**Comment by aturan23** [comment]
> I'm not sure, something is off with this component.
> Can you please share a code sandbox link with an example.

I'm sorry. But now it works. I don't know how. But between them is a very large distance...

**Comment by bietkul** [comment]
Closing it, seems it is not an issue with the library.
