### ISSUE TITLE
Not updating with react hooks

### ISSUE THREAD

**Issue by sayax** [bietkul/react-reactive-form#55]
**Describe the bug**
Field Group state not updating with react useState hook

**To Reproduce**
1) Create reactive form
2) create const [loading, setLoading] = useState(false)
3) create button
<Button disabled={!form.valid || loading} className="primary" onClick={submit} />
4) change state on click
const submit = () => {
setLoading(true);
}

**Expected behavior**
button disabled has loading = true state
**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sayax** [comment]
1.5) create form template

        <FieldGroup
          control={form}
          render={({ get, invalid }) => (
              <>
              <FieldControl
                name="username"
                render={({ handler, touched, hasError, meta }) => (
                <StyledFormField
                  error={
                    (touched && hasError('required') && 'required')
                  }
                >
                  <Input
                    as={MaskedInput}
                    mask={['+', '7', ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, ' ', /\d/, /\d/]}
                    placeholder=""
                    {...handler()}
                  />
                </StyledFormField>
                )}
              />
              <Button disabled={!form.valid || loading} className="primary" onClick={submit} />
              </>
          )}
        />

**Comment by bietkul** [comment]
By default, Field components only get re-render only when there is a change in the control's state.
It's recommended to not use the state under the Field component for better performance.
I can see that you're using a state variable named `loading`, it's better to put the `Button` component outside of the form, for example:
```js 
import { Field, ... } from 'react-reactive-form';
...
<>
  <FieldGroup
      control={form}
      render={({ get, invalid }) => (
          <>
          <FieldControl
            name="username"
            render={({ handler, touched, hasError, meta }) => (
            <StyledFormField
              error={
                (touched && hasError('required') && 'required')
              }
            >
              <Input
                as={MaskedInput}
                mask={['+', '7', ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, /\d/, ' ', /\d/, /\d/, ' ', /\d/, /\d/]}
                placeholder=""
                {...handler()}
              />
            </StyledFormField>
            )}
          />
          </>
      )}
    />
  <Field
    strict={false}
    control={form}
    render={({ invalid }) => <Button disabled={invalid || loading} className="primary" onClick={submit} />}
  />  
</>
```

If you still want to bypass it, please use `strict` prop as `false` in `FieldGroup` and `FieldControl` to avoid this default behavior, check [here](https://github.com/bietkul/react-reactive-form/blob/master/docs/api/FieldControl.md#props).
