### ISSUE TITLE
React 17 lifecycle support

### ISSUE THREAD

**Issue by jasperswart** [bietkul/react-reactive-form#57]
We really need React 17 lifecycle  support.

Is that something you are going to implement that quickly?

**Comment by GabLeRoux** [comment]
Here are related articles concerning react 17 lifecycle in case it helps:

* https://medium.com/@valerii.sukhov/react-17-lifecycle-5b68946c813c
* https://hackernoon.com/problematic-react-lifecycle-methods-are-going-away-in-react-17-4216acc7d58b

According to https://mdbootstrap.com/react-17/ react 17 was supposed to be out in late 2019

> React 17 release date
> The exact time of React 17 release hasn't been confirmed by the team yet, but it's generally expected to be out in 2019.

**Comment by bietkul** [comment]
@jasperswart Life cycle methods are already updated in the latest version. Can you please update?
Are you seeing any other errors or warnings then please share the error details.
