### ISSUE TITLE
Custom components are not rendered when state changes

### ISSUE THREAD

**Issue by geraldosalazar16** [bietkul/react-reactive-form#62]
**Describe the bug**
If you use a custom component inside a FieldControl, it only renders at the beginning, but after that, if you change the state, it will keep its initial values

**To Reproduce**
Here us a stackblitz showing the issue. I am using this library
https://github.com/JedWatson/react-select
So inside the render method of the form field, I am trying to use this component instead of a html select, and it takes the default options. In componentDidMount, I have set up a setTimeout to represent a API call, and after the timeout is finished, options are loaded but the component still shows no options
https://stackblitz.com/edit/react-myx6ak

**Expected behavior**
I expect that when the render function runs, the custom field should re-render

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by bietkul** [comment]
Use `strict` as `false` for that control. https://github.com/bietkul/react-reactive-form/issues/10#issuecomment-388720374

**Comment by bietkul** [comment]
![](https://i.imgur.com/vUs0ZyW.png)
