### ISSUE TITLE
When doing an optimised build I get the following error

### ISSUE THREAD

**Issue by Michael-D-Pine** [bietkul/react-reactive-form#7]
Hi,

I get the following error when doing an optimized build in a create-react-app.

"Failed to minify the code from this file"

        ./node_modules/react-reactive-form/src/model.js:41

Obviously works fine when just doing a "npm start" and running without any minification.

Using the following version
create-react-app 4.1.2
react 4.1.2
react.dom 4.1.2
react-scripts 4.1.2

cheers
Michael

**Comment by bietkul** [comment]
Thanks  @Michael-D-Pine for reporting the issue.
It has been fixed in the latest version.
