### ISSUE TITLE
React is outdated in console getting warnings

### ISSUE THREAD

**Issue by vforv** [bietkul/react-reactive-form#76]
react-dom.development.js:67 Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: FieldControl, FieldGroup

**Comment by bietkul** [comment]
Thanks for bringing this up. I'll fix it soon.

**Comment by vforv** [comment]
Thank you there is issue with Cotnext API is outdated.

Good work with plugin

**Comment by vforv** [comment]
Any update maybe regarding this?

**Comment by bostondevin** [comment]
Any update on this?

**Comment by bietkul** [comment]
`v2.0.0` is out with React 18.x support
