### ISSUE TITLE
Unable to install in project with react 18.2

### ISSUE THREAD

**Issue by codebysandip** [bietkul/react-reactive-form#85]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: react-ssr@1.0.0
npm ERR! Found: react@18.2.0
npm ERR! node_modules/react
npm ERR!   react@"^18.2.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^15.0.0-0 || ^16.4.0-0" from react-reactive-form@1.0.32
npm ERR! node_modules/react-reactive-form
npm ERR!   react-reactive-form@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by bietkul** [comment]
@sandip12081992 React 18 support is almost completed, a new version would be out in this week.

**Comment by codebysandip** [comment]
I Started using Formik but definitely i will try this lib also in my open source [React SSR Architecture](https://github.com/codebysandip/react-ssr)

**Comment by bietkul** [comment]
`v2.0.0` is out with React 18.x support
